### ISSUE TITLE
Doesn't work for `SopsSecret` resource

### ISSUE THREAD

**Issue by m0un10** [bryanl/manifest-summary#3]
Amazing tool! Use it every day. I recently discovered that it fails with [SopsSecret](https://github.com/isindir/sops-secrets-operator) resource. The error is
```
ERRO[0000] summarizing                                   error="creating summary for object: finding apiVersion"
```

Perhaps the encrypted part of the resource causes it grief?

Below is an example of the structure of a `SopsSecret` (with the encrypted parts omitted because i'm overly paranoid)
```
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: my-secret
spec:
  secretTemplates:
  - name: my-secret
    labels:
      app.kubernetes.io/managed-by: sops
    stringData:
      value: ENC[tag:OMITTED,tag:tag:OMITTED,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: tag:OMITTED
    created_at: "2022-01-31T02:49:44Z"
    enc: tag:OMITTED
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2022-01-31T02:49:45Z"
  mac: ENC[AES256_GCM,data:tag:OMITTED,tag:OMITTED,type:str]
  pgp: []
  encrypted_suffix: value
  version: 3.7.1
  ```
